package Pojo;
// Generated Jan 5, 2021 12:11:19 AM by Hibernate Tools 4.3.1



/**
 * Defaultimages generated by hbm2java
 */
public class Defaultimages  implements java.io.Serializable {


     private Integer id;
     private byte[] defaultImage;

    public Defaultimages() {
    }

    public Defaultimages(byte[] defaultImage) {
       this.defaultImage = defaultImage;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public byte[] getDefaultImage() {
        return this.defaultImage;
    }
    
    public void setDefaultImage(byte[] defaultImage) {
        this.defaultImage = defaultImage;
    }




}


