package Pojo;
// Generated Jan 5, 2021 12:11:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer id;
     private Users usersByToWho;
     private Users usersByFromWho;
     private String messageText;
     private Date sendTime;

    public Message() {
    }

    public Message(Users usersByToWho, Users usersByFromWho, String messageText, Date sendTime) {
       this.usersByToWho = usersByToWho;
       this.usersByFromWho = usersByFromWho;
       this.messageText = messageText;
       this.sendTime = sendTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsersByToWho() {
        return this.usersByToWho;
    }
    
    public void setUsersByToWho(Users usersByToWho) {
        this.usersByToWho = usersByToWho;
    }
    public Users getUsersByFromWho() {
        return this.usersByFromWho;
    }
    
    public void setUsersByFromWho(Users usersByFromWho) {
        this.usersByFromWho = usersByFromWho;
    }
    public String getMessageText() {
        return this.messageText;
    }
    
    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }




}


