package Pojo;
// Generated Jan 5, 2021 12:11:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String firstName;
     private String lastName;
     private String password;
     private byte[] profileImage;
     private Set messagesForToWho = new HashSet(0);
     private Set messagesForFromWho = new HashSet(0);

    public Users() {
    }

	
    public Users(String userName, String firstName, String lastName, String password, byte[] profileImage) {
        this.userName = userName;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.profileImage = profileImage;
    }
    public Users(String userName, String firstName, String lastName, String password, byte[] profileImage, Set messagesForToWho, Set messagesForFromWho) {
       this.userName = userName;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.profileImage = profileImage;
       this.messagesForToWho = messagesForToWho;
       this.messagesForFromWho = messagesForFromWho;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getProfileImage() {
        return this.profileImage;
    }
    
    public void setProfileImage(byte[] profileImage) {
        this.profileImage = profileImage;
    }
    public Set getMessagesForToWho() {
        return this.messagesForToWho;
    }
    
    public void setMessagesForToWho(Set messagesForToWho) {
        this.messagesForToWho = messagesForToWho;
    }
    public Set getMessagesForFromWho() {
        return this.messagesForFromWho;
    }
    
    public void setMessagesForFromWho(Set messagesForFromWho) {
        this.messagesForFromWho = messagesForFromWho;
    }




}


